"""Formosan UI labels and Whisper-to-NLLB language codes."""

LANGUAGE_GROUPS = {
    "阿美語 (’Amis)": [
        ("南勢阿美語", "ami-x-iams"),
        ("秀姑巒阿美語", "ami-x-skl"),
        ("海岸阿美語", "ami-x-pswl"),
        ("馬蘭阿美語", "ami-x-frng"),
        ("恆春阿美語", "ami-x-pld"),
    ],
    "泰雅語 (Tayal)": [
        ("賽考利克泰雅語", "tay-x-sql"),
        ("澤敖利泰雅語", "tay-x-sul"),
        ("四季泰雅語", "tay-x-cql"),
        ("宜蘭澤敖利泰雅語", "tay-x-kls"),
        ("汶水泰雅語", "tay-x-mtuw"),
        ("萬大泰雅語", "tay-x-plngw"),
    ],
    "排灣語 (Paiwan)": [
        ("東排灣語", "pwn-x-kcdsn"),
        ("北排灣語", "pwn-x-vnrn"),
        ("中排灣語", "pwn-x-pnvn"),
        ("南排灣語", "pwn-x-ynvl"),
    ],
    "布農語 (Bunun)": [
        ("卓群布農語", "bnn-x-td"),
        ("卡群布農語", "bnn-x-bkh"),
        ("丹群布農語", "bnn-x-vtn"),
        ("巒群布農語", "bnn-x-bnz"),
        ("郡群布農語", "bnn-x-isbk"),
    ],
    "卑南語 (Pinuyumayan)": [
        ("南王卑南語", "pyu-x-pym"),
        ("知本卑南語", "pyu-x-ktrp"),
        ("西群卑南語", "pyu-x-mkzy"),
        ("建和卑南語", "pyu-x-ksvk"),
    ],
    "魯凱語 (Rukai)": [
        ("東魯凱語", "dru-x-trmk"),
        ("霧臺魯凱語", "dru-x-ngdr"),
        ("大武魯凱語", "dru-x-lbw"),
        ("多納魯凱語", "dru-x-kgdv"),
        ("茂林魯凱語", "dru-x-tldr"),
        ("萬山魯凱語", "dru-x-opnh"),
    ],
    "鄒語 (Cou)": [("鄒語", "tsu")],
    "賽夏語 (SaySiyat)": [("賽夏語", "xsy")],
    "雅美語 (Yami)": [("雅美語", "tao")],
    "邵語 (Thau)": [("邵語", "ssf")],
    "噶瑪蘭語 (Kebalan)": [("噶瑪蘭語", "ckv")],
    "太魯閣語 (Truku)": [("太魯閣語", "trv-x-truku")],
    "撒奇萊雅語 (Sakizaya)": [("撒奇萊雅語", "szy")],
    "賽德克語 (Seediq/Seejiq/Sediq)": [
        ("都達賽德克語", "trv-x-td"),
        ("德固達雅賽德克語", "trv-x-tgdy"),
        ("德鹿谷賽德克語", "trv-x-trk"),
    ],
    "拉阿魯哇語 (Hla’alua)": [("拉阿魯哇語", "sxr")],
    "卡那卡那富語 (Kanakanavu)": [("卡那卡那富語", "xnb")],
}


DEFAULT_GROUP = next(iter(LANGUAGE_GROUPS))


# These are the language tokens used by the NLLB fine-tune. They are different
# from the Whisper language tokens above and follow the translation Space.
TRANSLATION_LANGUAGE_CODES = {
    "ami-x-iams": "ami_Sout",
    "ami-x-skl": "ami_Xiug",
    "ami-x-pswl": "ami_Coas",
    "ami-x-frng": "ami_Mala",
    "ami-x-pld": "ami_Heng",
    "tay-x-sql": "tay_Seko",
    "tay-x-sul": "tay_Zeao",
    "tay-x-cql": "tay_Four",
    "tay-x-kls": "tay_Yzea",
    "tay-x-mtuw": "tay_Wens",
    "tay-x-plngw": "tay_Wand",
    "pwn-x-kcdsn": "pwn_East",
    "pwn-x-vnrn": "pwn_Nrth",
    "pwn-x-pnvn": "pwn_Cent",
    "pwn-x-ynvl": "pwn_Sout",
    "bnn-x-td": "bnn_Zhuo",
    "bnn-x-bkh": "bnn_Kaqu",
    "bnn-x-vtn": "bnn_Tanq",
    "bnn-x-bnz": "bnn_Luan",
    "bnn-x-isbk": "bnn_Junq",
    "pyu-x-pym": "pyu_Nanw",
    "pyu-x-ktrp": "pyu_Zhib",
    "pyu-x-mkzy": "pyu_Xiqu",
    "pyu-x-ksvk": "pyu_Jian",
    "dru-x-trmk": "dru_East",
    "dru-x-ngdr": "dru_Wuta",
    "dru-x-lbw": "dru_Dawu",
    "dru-x-kgdv": "dru_Dona",
    "dru-x-tldr": "dru_Maol",
    "dru-x-opnh": "dru_Wans",
    "tsu": "tsu_Tsou",
    "xsy": "xsy_Sais",
    "tao": "tao_Yami",
    "ssf": "ssf_Thao",
    "ckv": "ckv_Kava",
    "trv-x-truku": "trv_Truk",
    "szy": "szy_Saki",
    "trv-x-td": "trv_Duda",
    "trv-x-tgdy": "trv_Tegu",
    "trv-x-trk": "trv_Delu",
    "sxr": "sxr_Saar",
    "xnb": "xnb_Kana",
}
