---
services:
  asr:
    image: registry.hf.space/ithuan-formosan-asr-srt:latest
    build: !reset null
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: always
  asr-kaldi:
    image: ithuan/formosan-ai:asr-kaldi
    build: !reset null
    restart: always
  tts:
    image: ithuan/formosan-ai:tts
    build: !reset null
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: always
